<?php
if( getenv('ENV_MODE') !== 'develop' ) :
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_55e3e21b665ec',
	'title' => 'Google',
	'fields' => array(
		array(
			'key' => 'field_55e3e21f02607',
			'label' => 'Search Console',
			'name' => 'hp_search_console',
			'type' => 'text',
			'instructions' => 'Search Consoleで発行される「HTMLタグ」を追加して所有者の確認ができます。表示されたMETAタグをここに貼り付けて下さい。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '<meta name="google-site-verification" content="発行された英数字の羅列が入っています" />',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55e3e56802608',
			'label' => 'Google Analytics',
			'name' => 'hp_google_analytics',
			'type' => 'text',
			'instructions' => 'Google Analyticsから発行されたトラッキングIDをここに貼り付けます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'options-google-code',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55797df517952',
	'title' => 'サロン情報を設定',
	'fields' => array(
		array(
			'key' => 'field_55798aad54438',
			'label' => '店舗',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_559cb0c142710',
			'label' => 'ロゴ画像',
			'name' => 'hp_salon_logo',
			'type' => 'image',
			'instructions' => 'お店のロゴ画像をアップします。サイズは自動で調整されます。<br>
推奨の画像サイズは「横幅は大きくても 400px」「高さ：100px以上」です。<br>
対応ファイルの種類「png、gif」のみで、背景は透過設定を推奨しています。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'logo',
			'library' => 'uploadedTo',
			'min_width' => '',
			'min_height' => 100,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'png,gif',
		),
		array(
			'key' => 'field_55798671325ef',
			'label' => 'サロン名',
			'name' => 'hp_salon_name',
			'type' => 'text',
			'instructions' => 'お店の名称を英字でご記入ください。英字ではなくカナ名しかない場合は、こちらにカナ名を入力頂き、下にある「サロン名（フリガナ）」は未入力状態にしてください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '例）HairsPress',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55c0295f79bfc',
			'label' => 'サロン名（フリガナ）',
			'name' => 'hp_salon_name_kana',
			'type' => 'text',
			'instructions' => 'お店の名称のフリガナを記入ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '例）ヘアーズプレス',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_557ba43fa4e92',
			'label' => 'コンセプト',
			'name' => 'hp_salon_concept',
			'type' => 'wysiwyg',
			'instructions' => 'お店のコンセプトを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_55979b63c6e18',
			'label' => 'ネット予約を選択',
			'name' => 'hp_webreserve_system',
			'type' => 'select',
			'instructions' => 'ご利用になられるWEB予約システムを選択ください。お持ちでない方は「なし」を選択。項目に該当していない場合は「その他」を選択ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'none' => 'なし',
				'reservia' => 'リザービア',
				'other' => 'その他',
			),
			'default_value' => array(
				'none' => 'none',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array(
			'key' => 'field_55979cecc6e19',
			'label' => 'ネット予約なし',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_55979b63c6e18',
						'operator' => '==',
						'value' => 'none',
					),
				),
			),
			'wrapper' => array(
				'width' => 75,
				'class' => '',
				'id' => '',
			),
			'message' => 'ネット予約のリンクを使用しない。お使いのWEB予約のURLをお持ちでしたら、上にある「ネット予約を選択」から選択ください。',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_55979d54c6e1a',
			'label' => '店舗番号',
			'name' => 'hp_salon_reservia',
			'type' => 'number',
			'instructions' => 'リザービアの管理画面から発行された「店舗番号」を入力ください。',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_55979b63c6e18',
						'operator' => '==',
						'value' => 'reservia',
					),
				),
			),
			'wrapper' => array(
				'width' => 75,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 123,
			'prepend' => '店舗番号',
			'append' => '',
			'min' => 1,
			'max' => 10000,
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_557a77b96e1d8',
			'label' => 'ネット予約URL',
			'name' => 'hp_salon_reserved',
			'type' => 'url',
			'instructions' => 'お使いのネット予約システムから発行されたURLを入力ください。',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_55979b63c6e18',
						'operator' => '==',
						'value' => 'other',
					),
				),
			),
			'wrapper' => array(
				'width' => 75,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_55798c9176535',
			'label' => '店舗連絡先',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_55798f783d7ba',
			'label' => '電話番号',
			'name' => 'hp_salon_telephone',
			'type' => 'text',
			'instructions' => 'お店の電話番号を入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '082-000-0000',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55798fca3d7bb',
			'label' => 'フリーダイアル',
			'name' => 'hp_salon_freedial',
			'type' => 'text',
			'instructions' => 'お店にフリーダイアルがある場合は入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '0120-000-000',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_592246fc2c5e9',
			'label' => 'フリーダイアル（地域指定）',
			'name' => 'hp_salon_freedial_region',
			'type' => 'true_false',
			'instructions' => 'フリーダイアルに地域指定をされているかたは、こちらをチェックしてください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '地域指定型または全国型',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '地域指定型',
			'ui_off_text' => '全国型',
		),
		array(
			'key' => 'field_55c0bc5339614',
			'label' => 'お店までのアクセス',
			'name' => 'hairs_route_text',
			'type' => 'textarea',
			'instructions' => 'お店までのアクセス経路を簡単に記入ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55798cd076536',
			'label' => '郵便番号',
			'name' => 'hp_salon_postalcode',
			'type' => 'text',
			'instructions' => 'お店の郵便番号を記入ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 40,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '730-0803',
			'prepend' => '〒',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_57319cc6599c8',
			'label' => '住所',
			'name' => 'hp_salon_address',
			'type' => 'text',
			'instructions' => '住所を入力してください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55c07d1a4e4ed',
			'label' => 'ズーム率',
			'name' => 'hp_salon_google_map_zoom',
			'type' => 'number',
			'instructions' => 'GoogleMapの表示時のズーム率の設定です。数字が小さいほど縮小し、大きいほど拡大されます。10〜20の間で設定できます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'default_value' => 16,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 10,
			'max' => 20,
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_559508bf2d884',
			'label' => 'Google Map',
			'name' => 'hp_salon_google_map',
			'type' => 'google_map',
			'instructions' => '住所で検索して、マーカーの位置を調整ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '34.3971924',
			'center_lng' => '132.4429794',
			'zoom' => 15,
			'height' => 360,
		),
		array(
			'key' => 'field_55c03b4eaed5e',
			'label' => '店舗の外観写真',
			'name' => 'hp_salon_shop_photo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'salon-info',
			'library' => 'uploadedTo',
			'min_width' => 480,
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg,JPG,jpeg,JPEG,png,PNG',
		),
		array(
			'key' => 'field_55c03cc35f0c8',
			'label' => '店舗の地図画像',
			'name' => 'hairs_mapimg_url',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'salon-info-map',
			'library' => 'uploadedTo',
			'min_width' => 480,
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg,JPG,jpeg,JPEG,png,PNG',
		),
		array(
			'key' => 'field_557990676e1d5',
			'label' => '営業時間・定休日',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_557990906e1d6',
			'label' => '定休日',
			'name' => 'hp_salon_holiday',
			'type' => 'text',
			'instructions' => 'お店の定休日を入力します。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '月曜日、第3日曜日',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55bc53971ae65',
			'label' => '営業時間（簡易）',
			'name' => 'hairs_opens_text',
			'type' => 'text',
			'instructions' => '簡易的な営業時間を設定します。フッターなどに表示されるパーツとなります。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '平日 9:00〜20:00　土日祝 10:00〜19:00など',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55c049300b3f6',
			'label' => '営業時間（詳細）',
			'name' => 'hairs_access_opens',
			'type' => 'textarea',
			'instructions' => 'お店の営業時間を詳しく入力ください。最終受付時間などもこちらに含める形で書くことができます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '【平日】


【日・祝】',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_557ba4b221ea2',
			'label' => 'ソーシャル設定',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_557ba6dc21ea5',
			'label' => 'Facebook',
			'name' => 'hp_salon_social_facebook',
			'type' => 'url',
			'instructions' => 'FacebookページのURLを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_557ba4c521ea3',
			'label' => 'Instagram',
			'name' => 'hp_salon_social_instagram',
			'type' => 'url',
			'instructions' => 'インスタグラムのURLを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_557ba54821ea4',
			'label' => 'twitter',
			'name' => 'hp_salon_social_twitter',
			'type' => 'url',
			'instructions' => 'ツイッターのURLを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_55b602634c163',
			'label' => 'LINE',
			'name' => 'hp_salon_social_line',
			'type' => 'url',
			'instructions' => 'LINE@のURLを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_557ba84e0000c',
			'label' => 'YouTube',
			'name' => 'hp_salon_social_youtube',
			'type' => 'url',
			'instructions' => 'YouTubeのURLを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_557ba7720000b',
			'label' => 'Google+',
			'name' => 'hp_salon_social_googleplus',
			'type' => 'url',
			'instructions' => 'Google+のURLを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_55b60f777e457',
			'label' => 'Pinterest',
			'name' => 'hp_salon_social_pinterest',
			'type' => 'url',
			'instructions' => 'PinterestのURLを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-salon-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55e6c460767c4',
	'title' => 'スタッフふりがな',
	'fields' => array(
		array(
			'key' => 'field_55951510eb90c',
			'label' => 'ふりがな',
			'name' => 'furigana',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '例）なまえ　たろう',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'staff',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'categories',
		11 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_557a95e7ee06d',
	'title' => 'スライダーの動作設定',
	'fields' => array(
		array(
			'key' => 'field_557a961377620',
			'label' => 'アニメーション',
			'name' => 'hp_slider_mode',
			'type' => 'select',
			'instructions' => 'スライダーの動きを設定します。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'slide' => 'スライド',
				'fade' => 'フェード',
				'verticalSlide' => 'ブラーフェード',
				'slideLeft' => '左へスライド',
				'slideRight' => '右へスライド',
				'slideRevealLeft' => 'Slide Reveal Left',
				'slideRevealRight' => 'Slide Reveal Right',
				'slideOverLeft' => 'Slide Over Left',
				'slideOverRight' => 'Slide Over Right',
				'expandReveal' => 'Expand Reveal',
				'shrinkReveal' => 'Shrink Reveal',
				'verticalSplitReveal' => 'Vertical Split Reveal',
				'horizontalSplitReveal' => 'Horizontal Split Reveal',
				'zipReveal' => 'Zip Reveal',
				'barReveal' => 'Bars Reveal',
				'fold' => '見開き',
				'foldLeft' => '左へ見開き',
				'foldRight' => '右へ見開き',
			),
			'default_value' => array(
				'fade' => 'fade',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_557a97672daf1',
			'label' => '速度',
			'name' => 'hp_slider_speed',
			'type' => 'number',
			'instructions' => 'アニメーションの速度を設定します。
「1000」で「1秒」となります。',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3500,
			'placeholder' => 1700,
			'prepend' => '',
			'append' => '',
			'min' => 500,
			'max' => 10000,
			'step' => 100,
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_557a98133d676',
			'label' => '停止時間',
			'name' => 'hp_slider_pause',
			'type' => 'number',
			'instructions' => '切り替わり時に一時停止する時間の長さです。
「1000」で「1秒」となります。',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 8000,
			'placeholder' => 5000,
			'prepend' => '',
			'append' => '',
			'min' => 500,
			'max' => 20000,
			'step' => 100,
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-slider-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_557a7f919f5fd',
	'title' => 'スライダー設定',
	'fields' => array(
		array(
			'key' => 'field_55fa2ce387046',
			'label' => '補足',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'アップロードできる画像の最小サイズがございますので、ご注意下さい。
最小の横幅は960px以上が必要になります。

<h4>推奨の画像サイズについて</h4>
<p><span style="color: #e22;">横幅：1280px　　高さ：545px</span></p>

上記サイズ内に写真を合わせることで、綺麗に収まります。',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_557a7fb9458ab',
			'label' => 'スライダー設定',
			'name' => 'hp_slider_settings',
			'type' => 'gallery',
			'instructions' => 'トップページに表示する写真を設定できます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => 6,
			'preview_size' => 'mio-slider-thumb',
			'library' => 'uploadedTo',
			'min_width' => 960,
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg,jpeg,png,JPG,JPEG,PNG',
			'insert' => 'append',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-slider-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55978bd6b78cd',
	'title' => 'チャンネル',
	'fields' => array(
		array(
			'key' => 'field_5597910eaf1a6',
			'label' => 'YouTube',
			'name' => 'hp_youtube_id',
			'type' => 'text',
			'instructions' => 'YouTubeの動画URLを入力ください。YouTube以外のURLが入力された場合は表示されません。',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://www.youtube.com/watch?v=ABCDEFG',
			'prepend' => 'URL',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55c9a0ed47e7b',
			'label' => '入力いただけるURLは以下の通りです。',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '①　https://www.youtube.com/watch?v=caHuis6aWAA
②　https://youtu.be/caHuis6aWAA',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'channel',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55952b2c50ea2',
	'title' => 'ヘアカタログ',
	'fields' => array(
		array(
			'key' => 'field_5595347bedffa',
			'label' => '基本情報',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5597af4054915',
			'label' => '担当者',
			'name' => 'cstaff',
			'type' => 'taxonomy',
			'instructions' => 'ヘアスタイルの担当者を選択してください。ここに担当者が含まれていない場合は、この項目の右側にプラスボタンがありますので、そちらから追加していただけます。',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'hpStaff',
			),
			'taxonomy' => 'com_category',
			'field_type' => 'radio',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_55952b5ad17d4',
			'label' => 'ヘアスタイルへのコメント',
			'name' => 'cappeal',
			'type' => 'textarea',
			'instructions' => 'ヘアスタイルに対してのアピールポイントやコメントなどを、自由にお書き下さい。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 6,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55db2d92691d8',
			'label' => 'レングス',
			'name' => 'hp_catalog_length',
			'type' => 'taxonomy',
			'instructions' => '髪の長さを該当するものにチェックしてください。複数選択も可能です。不必要な場合は、全てのチェックを外すことで「設定なし」となります。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'hpLength',
			),
			'taxonomy' => 'catalog_length',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_55952df7d17d6',
			'label' => 'カラー',
			'name' => 'ccolor',
			'type' => 'text',
			'instructions' => 'ヘアスタイルのカラーをご自由にお書き下さい。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '例）ブラウン・ベージュ系　など',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55952e22d17d7',
			'label' => 'パーマ',
			'name' => 'cparm',
			'type' => 'text',
			'instructions' => 'どのようなパーマをかけたかなどの情報をお書き下さい。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55952e46d17d8',
			'label' => 'イメージ',
			'name' => 'cimage',
			'type' => 'text',
			'instructions' => 'どのようなイメージでヘアスタイルをしたかなどを、ご自由にお書き下さい。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55e667b10c680',
			'label' => 'イメージタグ',
			'name' => 'hp_catalog_image_tag',
			'type' => 'taxonomy',
			'instructions' => 'ヘアスタイルのイメージをここに追加できます。この項目は、ヘアカタログの検索で使用しています。<br>
この項目の右側に（＋）マークが現れるので、そこからタグが追加できます。追加後はこの項目内にチェックができるリストで表示されます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'catalogImageTag',
			),
			'taxonomy' => 'catalog_tag',
			'field_type' => 'checkbox',
			'allow_null' => 1,
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_55952e6ad17d9',
			'label' => 'メニュー内容',
			'name' => 'cnaiyou',
			'type' => 'text',
			'instructions' => 'どのようなメニュー内容でスタイリングしたかを、ご自由にお書き下さい。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '例）カット＋カラー＋パーマ　など',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55952e9cd17da',
			'label' => '所要時間',
			'name' => 'ctime',
			'type' => 'text',
			'instructions' => '所要時間をお書き下さい。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '例）2時間　など',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55952fd8d17db',
			'label' => '料金',
			'name' => 'hp_catalog_money',
			'type' => 'number',
			'instructions' => '半角数字のみ入力ください。カンマは不用です。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '例）12000',
			'prepend' => '￥',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55953005d17dc',
			'label' => '( 〜 )を付ける',
			'name' => 'ckara',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'message' => '( 〜 )を付ける',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_55baf83c4cd79',
			'label' => '以前の料金項目',
			'name' => 'cmoney',
			'type' => 'text',
			'instructions' => 'システムが新しくなり、この項目に入力されている内容が使用できないため、この項目より上にある「所要時間」と「料金」の項目に新しく入力をお願い致します。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55953490edffb',
			'label' => '写真設定',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5595391fd03e0',
			'label' => '補足',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'ヘアスタイルの写真を<span style="color: #e00;">3枚</span>まで登録ができます。登録を行っていただくと、詳細ページにて各スタイルの表示をおこなえるようになります。<br>
使用できる写真は縦写真のみで、なるべく頭が中心より少し上ぐらいが丁度綺麗に収まります。<br>
横写真を登録した場合に、被写体の位置によっては違う位置で表示されてしまいます。',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_5597c24cd00c4',
			'label' => 'スタイル写真',
			'name' => 'catalog_photo_style',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => 3,
			'preview_size' => 'catalog-thumb',
			'library' => 'all',
			'min_width' => 320,
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpeg,jpg,png',
			'insert' => 'append',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'catalog',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'slug',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'categories',
		10 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55c8b6a35c555',
	'title' => '予約ボタン設定',
	'fields' => array(
		array(
			'key' => 'field_55953269683d1',
			'label' => 'ネット予約の設定',
			'name' => 'reserve_catalog',
			'type' => 'radio',
			'instructions' => 'ネット予約のボタンに設定されるリンクを選択してください。ただし、URL設定がされてなかった場合は何も表示されません。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'none' => 'なし',
				'shop' => '店舗用のURL',
				'staff' => 'スタッフ用のURL',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'shop',
			'layout' => 'horizontal',
			'allow_null' => 0,
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'catalog',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_559a7dce8739c',
	'title' => '担当者',
	'fields' => array(
		array(
			'key' => 'field_559a4240a4fe4',
			'label' => 'ヘアカタログと紐付け',
			'name' => 'staff_haircatalog_link',
			'type' => 'taxonomy',
			'instructions' => 'ヘアカタログのページにリンクを表示するのに使用します。
スタッフと担当者の項目は必ず同じものにチェックしてください。
',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'com_category',
			'field_type' => 'radio',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'staff',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55e84c9dc9aa3',
	'title' => '管理者設定',
	'fields' => array(
		array(
			'key' => 'field_559a896cbd1ee',
			'label' => 'ヘアカタログの使用方法',
			'name' => 'hp_reservia_catalog_check',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'hairspress' => 'HairsPressを使用する',
				'reservia' => 'Reserviaを使用する',
			),
			'default_value' => array(
				'hairspress' => 'hairspress',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_559793deb3f80',
			'label' => 'チャンネル投稿',
			'name' => 'hp_theme_channel_swich',
			'type' => 'true_false',
			'instructions' => 'チャンネルの投稿ページを表示する。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'message' => '表示する場合はチェックをしてください。',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_55e84e07726aa',
			'label' => '契約開始日',
			'name' => 'hp_service_start',
			'type' => 'date_picker',
			'instructions' => '契約開始日を設定します。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'Y年m月d日',
			'return_format' => 'Y-m-d',
			'first_day' => 0,
		),
		array(
			'key' => 'field_55fc138012155',
			'label' => 'リザービア番号を表示する',
			'name' => 'hp_reservia_number_check',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'リザービア番号を表示する',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_557a78f06e1db',
			'label' => 'メールアドレス',
			'name' => 'hp_salon_email',
			'type' => 'email',
			'instructions' => 'お申込み時にご記入頂いたメールアドレスを入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'sample@example.com',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'options-hairspress-setting',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55951502b4a68',
	'title' => 'スタッフ詳細項目',
	'fields' => array(
		array(
			'key' => 'field_55954589c1592',
			'label' => '基本設定',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_559516d0eb90d',
			'label' => '役職',
			'name' => 'manage',
			'type' => 'taxonomy',
			'instructions' => '登録する方の「役職」をチェックしてください。（複数可）　ここで役職を新たに追加も可能です。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'staffManage',
			),
			'taxonomy' => 'manage',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_559519a5ee765',
			'label' => '美容歴',
			'name' => 'beauty_history',
			'type' => 'number',
			'instructions' => '登録する方の「美容歴」を入力ください。非表示にしたい場合は、未入力にしてください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'beauty_history',
			),
			'default_value' => '',
			'placeholder' => 10,
			'prepend' => '美容歴',
			'append' => '年',
			'min' => 0,
			'max' => 50,
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55951a77ee767',
			'label' => '趣味',
			'name' => 'hobby',
			'type' => 'text',
			'instructions' => '登録される方の「趣味」をご自由に入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 70,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55951a08ee766',
			'label' => '得意なイメージ',
			'name' => 'good_image',
			'type' => 'text',
			'instructions' => '登録される方の「得意なイメージ」をご自由に入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'ナチュラル',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55951a9aee768',
			'label' => '得意な技術',
			'name' => 'good_technology',
			'type' => 'textarea',
			'instructions' => '登録される方の「得意な技術」をご自由に入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 120,
			'rows' => 4,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55953e7cd78d0',
			'label' => 'ブログリンク',
			'name' => 'blog_url_for',
			'type' => 'radio',
			'instructions' => '登録される方のブログリンクを設定することができます。<br>
URLを入力するか、カテゴリーから選択するかで下の項目が切り替わります。<br>
カテゴリーを選択した場合は、ブログのカテゴリーが選択できるようになります。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => 30,
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'URLを入力する' => 'URLを入力する',
				'カテゴリーから選択する' => 'カテゴリーから選択する',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_55953e48d78cf',
			'label' => 'URLの入力',
			'name' => 'blog_url_text',
			'type' => 'url',
			'instructions' => '登録される方のブログのURLを入力ください。非表示にする場合は、未入力にしてください。',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_55953e7cd78d0',
						'operator' => '!=',
						'value' => 'カテゴリーから選択する',
					),
				),
			),
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_55951b7cee769',
			'label' => 'カテゴリーから選択',
			'name' => 'blog_url_select',
			'type' => 'taxonomy',
			'instructions' => '当システムのブログに登録されているカテゴリーからリンクを設定します。',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_55953e7cd78d0',
						'operator' => '==',
						'value' => 'カテゴリーから選択する',
					),
				),
			),
			'wrapper' => array(
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array(
			'key' => 'field_55951be7ee76a',
			'label' => 'コメント',
			'name' => 'appeal',
			'type' => 'textarea',
			'instructions' => '登録される方のアピールなどのコメントをご自由に入力ください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_559529dfada18',
			'label' => 'ネット予約URL',
			'name' => 'reserve_staff',
			'type' => 'url',
			'instructions' => '（※任意）登録される方のWEB予約URLを設定できます。ご利用になられている予約システムからURLを発行してください。　ヘアカタログの投稿で使用方法を決めることができます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_57426c7bf56d5',
			'label' => '予約ボタンの非表示',
			'name' => 'reserve_btn_hidden',
			'type' => 'true_false',
			'instructions' => '予約ボタンを非表示にしたい場合には、チェックをしてください。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '予約ボタンを非表示にする',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5595459fc1593',
			'label' => 'ソーシャル設定',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_55daf39a216ab',
			'label' => '補足',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '各ソーシャルのURLを設定できます。
お持ちでない場合は未入力のままで問題ありません。

※各項目は任意で入力ください。',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_5595460fc1596',
			'label' => 'Facebook',
			'name' => 'staff_facebook',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_559545c0c1594',
			'label' => 'Instagram',
			'name' => 'staff_instagram',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_559545fbc1595',
			'label' => 'twitter',
			'name' => 'staff_twitter',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_55c5e4c700342',
			'label' => 'LINE',
			'name' => 'staff_line',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_55954651c1598',
			'label' => 'YouTube',
			'name' => 'staff_youtube',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_5595461fc1597',
			'label' => 'Google+',
			'name' => 'staff_google_plus',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
		array(
			'key' => 'field_55954663c1599',
			'label' => 'Pinterest',
			'name' => 'staff_pinterest',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'staff',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'categories',
		11 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_559501f2e4752',
	'title' => 'フリースペース',
	'fields' => array(
		array(
			'key' => 'field_55fc1cd06daeb',
			'label' => 'フリースペースとは？',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'フリースペースとは、トップページにバナーを付けてリンクすることのできる設定です。
最大で3個までリンクを設定することができます。

例としては、「キャンペーン告知をしたい！」「もっとこのページを見てほしい！」などなど、使い方はあると思いますので、是非活用してみてください。',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_55950b794fe28',
			'label' => '表示の設定',
			'name' => 'free_space_hidden',
			'type' => 'true_false',
			'instructions' => 'トップページにフリースペースを表示するか設定できます。<br>
チェックを外すと、非表示に出来ます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '表示する',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_559501fba95c2',
			'label' => 'フリースペース',
			'name' => 'free_space',
			'type' => 'flexible_content',
			'instructions' => 'トップページにバナーなどが設置できるフリースペースを設定できます。<br>
',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_55950b794fe28',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'freepage',
			),
			'button_label' => 'スペースの追加',
			'min' => '',
			'max' => 3,
			'layouts' => array(
				array(
					'key' => '55950253e9d89',
					'name' => 'フリースペース',
					'label' => 'フリースペース',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_559503f8115ea',
							'label' => '画像',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '写真やバナーをアップロードまたは設定できます。',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'uploadedTo',
							'min_width' => 320,
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpeg,JPEG,jpg,JPG,png,PNG',
						),
						array(
							'key' => 'field_559505f0115eb',
							'label' => 'リンクテキスト',
							'name' => 'link_text',
							'type' => 'text',
							'instructions' => 'テキストを表示する場合は、ご入力ください。',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'link_text',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'ヘアカタログ',
							'prepend' => '',
							'append' => '',
							'maxlength' => 14,
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_55d6d95ff8170',
							'label' => 'URLを入力する',
							'name' => 'url_customer',
							'type' => 'true_false',
							'instructions' => 'URLを入力したい場合に、チェックしてください。下にある項目が切り替わります。',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'URLを入力する',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_55d6d9ccf8171',
							'label' => 'ページ選択',
							'name' => 'url_selector',
							'type' => 'page_link',
							'instructions' => 'リンクしたいページを選択してください。',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_55d6d95ff8170',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'freepage',
								1 => 'page',
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'allow_archives' => 1,
						),
						array(
							'key' => 'field_55950276a95c3',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'url',
							'instructions' => 'URLを記入ください。',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_55d6d95ff8170',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
						),
						array(
							'key' => 'field_55e8227cea3b8',
							'label' => 'リンクの動作',
							'name' => 'link_target',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '新規ウィンドウ(タブ)で開く',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-salon-freespace',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55bf6b05ec0f4',
	'title' => 'メニューカナ名',
	'fields' => array(
		array(
			'key' => 'field_55bf65cbb7d9f',
			'label' => 'フリガナなど',
			'name' => 'hp_menu_kananame',
			'type' => 'text',
			'instructions' => 'メニュー名のフリガナなど。メニュータイトルより小さめのテキストで表示されます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'menu',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_55bf501068f0f',
	'title' => 'メニュー',
	'fields' => array(
		array(
			'key' => 'field_5c63deff9e880',
			'label' => 'メニュー',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_55bf6636b7da0',
			'label' => 'メニュー',
			'name' => 'hp_menu_list',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'メニュー項目を追加',
			'sub_fields' => array(
				array(
					'key' => 'field_55bf66c6b7da1',
					'label' => 'メニュー名',
					'name' => 'menu_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '例）カット（SB込み）',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_55bf6882b7da3',
					'label' => '施術時間',
					'name' => 'menu_time',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '分単位で入力ください。',
					'prepend' => '',
					'append' => '分',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_55bf67f9b7da2',
					'label' => '説明',
					'name' => 'menu_etc_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_55bf6904b7da4',
					'label' => '金額',
					'name' => 'menu_price',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '数字を入力ください',
					'prepend' => '¥',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_55bf6991b7da5',
					'label' => '〜',
					'name' => 'menu_kara',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '10',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_55e70996944da',
					'label' => '最大金額',
					'name' => 'menu_price_end',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_55bf6991b7da5',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '数字を入力ください',
					'prepend' => '¥',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
			),
		),
		array(
			'key' => 'field_5c63dee89e87f',
			'label' => '備考欄',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_55bf6a0cb7da6',
			'label' => '備考欄',
			'name' => 'hp_menu_other_text',
			'type' => 'textarea',
			'instructions' => '表示位置は、当該メニューの下に表示されます。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'menu',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

endif;
endif; // ローカルで実行しない
