<?php

// new Lira_Conf;
return array(
	'nav_primary' => array(
		'theme_location' => 'primary',
		'menu'           => 'primary',
		'container'      => false,
		'menu_class'     => 'navi-list',
		'items_wrap'     => '<ul id="%1$s" class="%2$s"><li class="home-navi'.( is_front_page() && is_home() ? ' current-menu-item' : '' ).'"><a href="'.esc_url( home_url( '/' ) ).'">トップページ</a></li>%3$s</ul>',
	),
	'nav_secondary' => array(
		'theme_location' => 'secondary',
		'container'      => false,
		'menu_class'     => 'sub-navi',
		'depth'          => 1,
		'link_before'    => '<span class="screen-text">',
		'link_after'     => '</span>',
		// 'items_wrap'     => '<ul id="%1$s" class="%2$s">%3$s</ul>',
	),
	'nav_social' => array(
		'theme_location' => 'social',
		'container'      => false,
		'menu_class'     => 'social-list social-icon',
		'depth'          => 1,
		'link_before'    => '<span class="screen-reader-text">',
		'link_after'     => '</span>',
		'depth'          => 1,
		// 'items_wrap'     => '<ul id="%1$s" class="%2$s">%3$s</ul>',
	),

	'widgets' => array(
		'sidebar_blog_top' => array(
			'name'          => 'サイドバー上部',
			'id'            => 'blog-sidebar-top-widget',
			'description'   => 'ブログのサイドバー上部のウィジェットエリアです。',
			'before_widget' => '<div id="%1$s" class="widget %2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h3 class="widgettitle heading-mark"><span class="f-um">',
			'after_title'   => '</span></h3>',
		),
		'sidebar_blog_bottom' => array(
			'name'          => 'サイドバー下部',
			'id'            => 'blog-sidebar-bottom-widget',
			'description'   => 'ブログのサイドバー下部のウィジェットエリアです。',
			'before_widget' => '<div id="%1$s" class="widget %2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h3 class="widgettitle heading-mark"><span class="f-um">',
			'after_title'   => '</span></h3>',
		),
	),

	'form' => array(
		'prefecture' => array(
			'1'  => '北海道',
			'2'  => '青森県',
			'3'  => '岩手県',
			'4'  => '宮城県',
			'5'  => '秋田県',
			'6'  => '山形県',
			'7'  => '福島県',
			'8'  => '茨城県',
			'9'  => '栃木県',
			'10' => '群馬県',
			'11' => '埼玉県',
			'12' => '千葉県',
			'13' => '東京都',
			'14' => '神奈川県',
			'15' => '新潟県',
			'16' => '富山県',
			'17' => '石川県',
			'18' => '福井県',
			'19' => '山梨県',
			'20' => '長野県',
			'21' => '岐阜県',
			'22' => '静岡県',
			'23' => '愛知県',
			'24' => '三重県',
			'25' => '滋賀県',
			'26' => '京都府',
			'27' => '大阪府',
			'28' => '兵庫県',
			'29' => '奈良県',
			'30' => '和歌山県',
			'31' => '鳥取県',
			'32' => '島根県',
			'33' => '岡山県',
			'34' => '広島県',
			'35' => '山口県',
			'36' => '徳島県',
			'37' => '香川県',
			'38' => '愛媛県',
			'39' => '高知県',
			'40' => '福岡県',
			'41' => '佐賀県',
			'42' => '長崎県',
			'43' => '熊本県',
			'44' => '大分県',
			'45' => '宮崎県',
			'46' => '鹿児島県',
			'47' => '沖縄県',
		),
	),
);

